-- MySQL Script generated by MySQL Workbench
-- Tue Oct  4 15:41:09 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema colin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colin` DEFAULT CHARACTER SET utf8 ;
USE `colin` ;

-- -----------------------------------------------------
-- Table `colin`.`tpbt_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_teams` (
  `id_team` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_team`),
  UNIQUE INDEX `id-team_UNIQUE` (`id_team` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `login` (`login` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_projects` (
  `id_project` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `site` TEXT NOT NULL,
  `admin` INT(11) NOT NULL,
  `id_team` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_project`, `admin`),
  UNIQUE INDEX `id_UNIQUE` (`id_project` ASC),
  INDEX `fk_tpbt_projects_tpbt_team1_idx` (`id_team` ASC),
  INDEX `fk_tpbt_projects_tpbt_users1_idx` (`admin` ASC),
  CONSTRAINT `fk_tpbt_projects_tpbt_team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `colin`.`tpbt_teams` (`id_team`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_projects_tpbt_users1`
    FOREIGN KEY (`admin`)
    REFERENCES `colin`.`tpbt_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_states` (
  `id_state` INT(11) NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_state`),
  UNIQUE INDEX `id_UNIQUE` (`id_state` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_bugs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_bugs` (
  `id_bug` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `date_start` DATETIME NOT NULL,
  `date_end` DATETIME NULL DEFAULT NULL,
  `tpbt_states_id_state` INT(11) NOT NULL,
  `id_project` INT(11) NOT NULL,
  `users_id_admin` INT(11) NOT NULL,
  `users_id_assin` INT(11) NOT NULL,
  PRIMARY KEY (`id_bug`),
  UNIQUE INDEX `id_UNIQUE` (`id_bug` ASC),
  INDEX `fk_tpbt_bugs_tpbt_projects1_idx` (`id_project` ASC),
  INDEX `fk_tpbt_bugs_tpbt_states1_idx` (`tpbt_states_id_state` ASC),
  INDEX `fk_tpbt_bugs_tpbt_users1_idx` (`users_id_admin` ASC),
  INDEX `fk_tpbt_bugs_tpbt_users2_idx` (`users_id_assin` ASC),
  CONSTRAINT `fk_tpbt_bugs_tpbt_projects1`
    FOREIGN KEY (`id_project`)
    REFERENCES `colin`.`tpbt_projects` (`id_project`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_bugs_tpbt_states1`
    FOREIGN KEY (`tpbt_states_id_state`)
    REFERENCES `colin`.`tpbt_states` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_bugs_tpbt_users1`
    FOREIGN KEY (`users_id_admin`)
    REFERENCES `colin`.`tpbt_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_bugs_tpbt_users2`
    FOREIGN KEY (`users_id_assin`)
    REFERENCES `colin`.`tpbt_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_bugs_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_bugs_comments` (
  `id_comment` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `id_user` INT(11) NOT NULL,
  `bugs_id_bug` INT(11) NOT NULL,
  PRIMARY KEY (`id_comment`),
  UNIQUE INDEX `id_UNIQUE` (`id_comment` ASC),
  INDEX `fk_tpbt_comments_tpbt_users1_idx` (`id_user` ASC),
  INDEX `fk_tpbt_comments_tpbt_bugs1_idx` (`bugs_id_bug` ASC),
  CONSTRAINT `fk_tpbt_comments_tpbt_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `colin`.`tpbt_users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_comments_tpbt_bugs1`
    FOREIGN KEY (`bugs_id_bug`)
    REFERENCES `colin`.`tpbt_bugs` (`id_bug`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colin`.`tpbt_teams_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colin`.`tpbt_teams_users` (
  `id_user` INT(11) NOT NULL,
  `id_team` INT(11) NOT NULL,
  INDEX `fk_tpbt_team_has_tpbt_users_tpbt_users1_idx` (`id_user` ASC),
  INDEX `fk_tpbt_team_has_tpbt_users_tpbt_team1_idx` (`id_team` ASC),
  CONSTRAINT `fk_tpbt_team_has_tpbt_users_tpbt_team1`
    FOREIGN KEY (`id_team`)
    REFERENCES `colin`.`tpbt_teams` (`id_team`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tpbt_team_has_tpbt_users_tpbt_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `colin`.`tpbt_users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
